spring.application.name=service

# H2
spring.datasource.url=jdbc:h2:mem:frauddb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# JWT ? generi?i random Base64 string od min 256 bita
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgZnJhdWRndWFyZA==
jwt.expiration-ms=86400000

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true